//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a scaffolding tool.
//     Runtime Version: $Version$
//     Date: $DateTimeNow$
// </auto-generated>
//------------------------------------------------------------------------------
namespace $ModuleNamespace$.Service
{
    using Core.Repositories;
    using Models;
    
    public interface I$ServiceName$Repository :
        ICrudRepository<$ServiceName$, $ServiceModelName$, long>
    {
    }
}
