--------------------------------------------------------------------------------
-- <auto-generated>
--     This code was generated by a scaffolding tool.
--     Runtime Version: $Version$
--     Date: $DateTimeNow$
-- </auto-generated>
--------------------------------------------------------------------------------
PRINT 'Creating the $TableName$ table...'
GO

if not exists (select * from sys.tables where name = '$TableName$' and schema_name(schema_id) = '$TableSchema$') begin
CREATE TABLE [$TableSchema$].[$TableName$]
(
    $first(TableColumns): { col | [$col.Name$] $col.SqlType$ IDENTITY(1,1) NOT NULL, }$
    $rest(TableColumns): { col | [$col.Name$] $col.SqlType$,}; separator="\n"$
    CONSTRAINT PK_$TableName$ PRIMARY KEY CLUSTERED (Id) ON [PRIMARY]
)
end;
go
