//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a scaffolding tool.
//     Runtime Version: $Version$
//     Date: $DateTimeNow$
// </auto-generated>
//------------------------------------------------------------------------------
namespace $ModuleNamespace$.DataAccess
{
    using $ModuleNamespace$.Models;
    using Se.Core.DataAccess;
    
    public interface I$ServiceName$Provider : ICrudProvider<$ServiceModelName$, long>
    {
    }
}
